### ISSUE TITLE
Background Correction only Partially Applied

### ISSUE THREAD

**Issue by u8sand** [MaayanLab/speedrichr#1]
https://github.com/MaayanLab/speedrichr/blob/50ee77074483dae319a245f97417a4d91afc3f97/src/main/java/serv/EnrichmentCore.java#L921-L962

Though the genes not in the background seem to be removed, and the "filteredGmtSize" computed, it's not actually used for anything--I would have expected it to be used in the fisher test calculation, potentially also adopting "totalBgGenes" as `_background.length`.

Please advise when you get a chance @lachmann12 

Note, my proposed fix would be:
```diff
-					int numGenelist = _geneset.length;
+					int numGenelist = genesetSet.size();
-	    			int totalBgGenes = 20000;
+	    			int totalBgGenes = _background.size();
-	    			int gmtListSize =  gmtlist.genearray.length;
+	    			int gmtListSize =  filteredGmtSize;
```

**Comment by lachmann12** [comment]
I will check on it after the weekend
